- name: Terraform Apply
  run: |
    cd terraform
    terraform apply -auto-approve \
      -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
      -var "service_account_email=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}"
  
  # Optional: Add a step to show Terraform output
  - name: Show Terraform Output
    run: |
      cd terraform
      terraform output